name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pytest httpx pip-audit
      - name: Run unit tests
        env:
          OPENAI_API_KEY: test
          CHAT_API_KEY: test-key
        run: pytest -q
      - name: pip-audit (report only)
        run: pip-audit -r requirements.txt || true
